# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.

# Add steps that build, run tests, deploy, and more:

# https://aka.ms/yaml

 

trigger:

- master

variables:

- name: System.Debug

  value: true

jobs:

- job: Job_1

  displayName: Agent job 1

  pool:

    name: Default

  steps:

  - checkout: self

    clean: true

    fetchTags: false

  - task: Application security testing@2023

    displayName: AdoBuilds_2023.3.4_SanityTest_WithYaml

    inputs:
      projectName: 'ADOYAML'
      enableProxy: false
      enableSastScan: true
      CheckmarxService: 'Sast95'
      fullTeamName: 'CxServer'
      incScan: false
      generatePDFReport: true
      enableDependencyScan: true
      dependencyServerURL: 'ScaCredential'
      scaTeam: 'CxServer'
      includeSource: true