# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.

# Add steps that build, run tests, deploy, and more:

# https://aka.ms/yaml

 

trigger:

- master

variables:

- name: System.Debug

  value: true

jobs:

- job: Job_1

  displayName: Agent job 1

  pool:

    name: Default

  steps:

  - checkout: self

    clean: true

    fetchTags: false

  - task: Application security testing@2023

    displayName: AdoBuilds_2023.3.4_SanityTest_WithYaml

    inputs:

      projectName: AdoBuilds_2023.3.4_SanityTestWithYaml

      enableSastScan: true
      CheckmarxService: 881329b2-47c1-4fa3-b8b9-b98f6c593b97
      fullTeamName: CxServer

      fullScansScheduled: false

      enableDependencyScan: true

      dependencyServerURL: 2d7c733d-cb24-4f72-af8c-55bbbdeb3c9e

      scaTeam: /CxServer

      isEnableScaResolver: true

      pathToScaResolver : 'C:\ADO_Plugin_Testing\Ado_ScaResolver\ScaResolver-win64'

      scaResolverAddParameters: -s C:\SourceCode\JavaVulnerableLabE-master -n AdoScaResolver_SanityTestWithYaml --resolver-result-path C:\ADO_Plugin_Testing\Ado_ScaResolver\ScaResolverResults\AdoScaResolver_SanityTestWithYaml.json --log-level Debug