resources:
  repositories:
  - repository: self
    type: git
    ref: master
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: Default
  steps:
  - checkout: self
    clean: true
  - task: Checkmarx-Prerelease.cxsast.cx-scan-task.Application security testing@2022
    displayName: 'Application security testing'
    inputs:
    projectName: testYaml92
    CheckmarxService: sast9dot5
    fullTeamName: CxServer
    incScan: false
    scanTimeout: 20
    comment: test
    generatePDFReport: true
    vulnerabilityThreshold: true
    high: 400
    medium: 400
    low: 400
