resources:
  repositories:
  - repository: self
    type: git
    ref: master
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: Default
  steps:
  - checkout: self
    clean: true  
  - task: Checkmarx-Prerelease.cxsast.cx-scan-task.Application security testing@2022
  	displayName: 'Application security testing'
  	input: 
     projectName: DPViolations001
     CheckmarxService: sast9dot5
     engineConfigId: 1
     fullTeamName: CxServer
     incScan: false
     enablePolicyViolations: true
