stages:
- stage: Deploy
  pool: 
   name: Default
   demands:
    - agent.name -equals agentOct1
  jobs:
  - job: BuildJob
	steps:
	- task: Checkmarx-Prerelease.cxsast.cx-scan-task.Application security testing@2022
  displayName: 'Application security testing'
  inputs:
    projectName: DPViolations001
    CheckmarxService: sast9dot5
    engineConfigId: 1
    fullTeamName: CxServer
    incScan: false
    enablePolicyViolations: true
